---
- hosts: all
  remote_user: root
  become: yes
  become_user: root
 
  tasks: 
    - name: manage user and group memebership
      user:
        name: "{{ item.name }}"
        state: present
        group: "{{ item.groups }}"
      with_items:
        - { name: 'linda', groups: 'students1' }
        - { name: 'anna', groups: 'profs1' }

